name: CI and Deployment Workflow

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    name: Execute Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Unit Tests
        run: npm run test

  e2e-tests:
    name: Execute End-to-End Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set Up Database
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          cat .env
          export $(cat .env | xargs)
          npx prisma db push

      - name: Reset Database Before Tests
        run: |
          echo "Resetting Database..."
          npx prisma migrate reset --force

      - name: Compile Next.js App
        run: npm run build

      - name: Start Next.js Server
        run: |
          nohup npm run start -- -p 3000 > nextjs.log 2>&1 &
          sleep 5
        env:
          NODE_ENV: production
          PORT: 3000

      - name: Print Next.js Logs if Server Fails
        if: failure()
        run: cat nextjs.log

      - name: Wait for Next.js Server to Start
        run: |
          echo "Waiting for Next.js to start..."
          for i in {1..60}; do
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000 || echo "000")
            if [[ "$STATUS_CODE" == "200" ]]; then
              echo "Next.js is up!"
              break
            fi
            echo "Still waiting... ($i)"
            sleep 2
          done
        timeout-minutes: 3

      - name: Run Playwright Tests
        run: E2E_TEST=true npm run test:e2e

      - name: Upload Playwright Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/

  deploy-to-vercel:
    name: Deploy Application to Vercel
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Project Dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build the Application
        run: npm run build

      - name: Trigger Vercel Production Deployment 
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
