name: Vercel Deployment Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  deploy-to-vercel:
    name: Deploy Application to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Project Dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build the Application
        run: npm run build

      - name: Trigger Vercel Production Deployment 
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
